a=5
b="Chihiro"
c=True
d=6.6
e="True"
f="Silenci"
g=4352
h="iral"
i=False
j="iasas"
a=type(a); print(a)
a=type(b); print(b)
a=type(c); print(c)
a=type(d); print(d)
a=type(e); print(e)
a=type(f); print(f)
a=type(g); print(g)
a=type(h); print(h)
a=type(i); print(i)
a=type(j); print(j)